services:
  - type: web
    name: openlist
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    ports:
      - port: 5244
        protocol: tcp
    disk:
      name: openlist-data
      mountPath: /opt/openlist/data
      sizeGB: 1
    envVars:
      - key: UMASK
        value: "022"
